rename project to poissonsearch-oss

diff --git a/distribution/src/bin/elasticsearch-env b/distribution/src/bin/elasticsearch-env
--- a/distribution/src/bin/elasticsearch-env
+++ b/distribution/src/bin/elasticsearch-env
@@ -50,8 +50,13 @@ else
 fi
 
 if [ ! -x "$JAVA" ]; then
-    echo "could not find java in $JAVA_TYPE at $JAVA" >&2
-    exit 1
+    echo "could not find java in $JAVA_TYPE at $JAVA, try use system install java" >&2
+    java --version
+    if [ $? -ne 0 ]; then
+      echo "could not find system java, please specify JAVA_HOME" >&2
+      exit 1
+    fi
+    JAVA="java"
   fi
 
 # do not let JAVA_TOOL_OPTIONS slip in (as the JVM does by default)
